### ISSUE TITLE
Several controls are not exposed in dist

### ISSUE THREAD

**Issue by mootari** [wearekuva/oui#20]
Currently the only exposed controls are: ColorPicker, ComboBox, Graph, XYPad.

NumericStepper, Dial or Button (and possibly several others, e.g. TextInput) are still missing and can therefore not be set via datoui.

**Comment by mootari** [comment]
I also noticed that the annotation property "includeStepper" seems to have no effect. Might be caused by the above bug.

**Comment by mootari** [comment]
Just took a stab at including DIal and noticed that it's actually using react. I assume Dial (and probably several others) are cruft/leftovers that haven't been migrated to preact and therefore left out intentionally?

**Comment by marklundin** [comment]
Yes, the Dial is a not quite complete at the moment, and yes everything was originally built on React, however the 600kb didn't quite cut it, so we opted for Preact which has a much smaller footprint with similar functionality

**Comment by mootari** [comment]
Thanks for the feedback. I'm still catching up, but I'm slowly getting an idea of the overall structure and intentions. Having issues for quirks or tasks you're aware of would be helpful though.

Oh, and thanks for sharing your work! I'd love to see this library getting more traction.

**Comment by marklundin** [comment]
Fixed in dbc8aa2

**Comment by mootari** [comment]
One down, three to go. Button, Checkbox and TextInput are still missing. :)
